const stocks = [
    {symbol: "AAPL", name: "Apple Inc.", currentPrice: 150.25},
    {symbol: "GOOGL", name: "Alphabet Inc.", currentPrice: 950.25},
    {symbol: "MSFT", name: "Microsoft Corporation", currentPrice: 65.25},
    {symbol: "AMZN", name: "Amazon.com Inc.", currentPrice: 985.25},
    {symbol: "FB", name: "Facebook Inc.", currentPrice: 150.25},
    {symbol: "TWTR", name: "Twitter Inc.", currentPrice: 19.25},
    {symbol: "SNAP", name: "Snap Inc.", currentPrice: 15.25},
    {symbol: "TSLA", name: "Tesla Inc.", currentPrice: 300.25},
    {symbol: "NFLX", name: "Netflix Inc.", currentPrice: 150.25},
    {symbol: "NVDA", name: "NVIDIA Corporation", currentPrice: 150.25},
    {symbol: "INTC", name: "Intel Corporation", currentPrice: 150.25},
    {symbol: "QCOM", name: "QUALCOMM Inc.", currentPrice: 150.25},
    {symbol: "CSCO", name: "Cisco Systems Inc.", currentPrice: 150.25},
    {symbol: "ORCL", name: "Oracle Corporation", currentPrice: 150.25},
    {symbol: "IBM", name: "International Business Machines Corporation", currentPrice: 150.25},
    {symbol: "HPQ", name: "HP Inc.", currentPrice: 150.25},
    {symbol: "HPE", name: "Hewlett Packard Enterprise Company", currentPrice: 150.25},
    {symbol: "VMW", name: "VMware Inc.", currentPrice: 150.25},
    {symbol: "EMC", name: "EMC Corporation", currentPrice: 150.25},
    {symbol: "RHT", name: "Red Hat Inc.", currentPrice: 150.25},
    {symbol: "SAP", name: "SAP SE", currentPrice: 150.25},
    {symbol: "ADBE", name: "Adobe Systems Incorporated", currentPrice: 150.25},
    {symbol: "CRM", name: "Salesforce.com Inc.", currentPrice: 150.25},
    {symbol: "BABA", name: "Alibaba Group Holding Limited", currentPrice: 150.25},
    {symbol: "TCEHY", name: "Tencent Holdings Limited", currentPrice: 150.25},
    {symbol: "BIDU", name: "Baidu Inc.", currentPrice: 150.25},
    {symbol: "JD", name: "JD.com Inc.", currentPrice: 150.25},
    {symbol: "TWX", name: "Time Warner Inc.", currentPrice: 150.25},
    {symbol: "FOXA", name: "Twenty-First Century Fox Inc.", currentPrice: 150.25},
    {symbol: "DIS", name: "The Walt Disney Company", currentPrice: 150.25},
    {symbol: "CMCSA", name: "Comcast Corporation", currentPrice: 150.25},
    {symbol: "CBS", name: "CBS Corporation", currentPrice: 150.25},
    {symbol: "VIAB", name: "Viacom Inc.", currentPrice: 150.25},
    {symbol: "DISCA", name: "Discovery Communications Inc.", currentPrice: 150.25},
    {symbol: "DISCK", name: "Discovery Communications Inc.", currentPrice: 150.25}
  ];
  
  export default stocks;
  